### PR TITLE
[Fix #11] Fix Bundler autorequire paths for smtpapi extension

### LINKED ISSUE #11: Undefined Method `smtpapi` for an instance of Mail::Message
# System Information
- Ruby 3.3.5
- Rails 7.1.5.1
- Mac OS 15.5 (24F74)

# Steps to Reproduce
- `rails new mailer-test`
- add gem to Gemfile `gem "mail-x_smtpapi-ksr"` and `bundle install`
- add random mailer under mailers
```
class RandomMailer < ApplicationMailer
  default from: 'notifications@example.com'
  
  def welcome_email(recipient)
    @recipient = recipient
    @url = 'http://example.com/login'
    
    # Set the SMTP API category to 'test'
    mail.smtpapi.category = 'test'
    
    mail(
      to: recipient,
      subject: 'Welcome to Our Application!'
    )
  end
end
```

- start `rails console`
```
mail = RandomMailer.welcome_email('test@example.com')
puts mail.to_s
```

`app/mailers/random_mailer.rb:9:in `welcome_email': undefined method `smtpapi' for an instance of Mail::Message (NoMethodError)`

This was experienced in a production app:
```
NoMethodError: undefined method `smtpapi' for an instance of Mail::Message
from /bundle/ruby/3.3.0/gems/mail-2.8.1/lib/mail/message.rb:1389:in `method_missing'
```

before testing on the new rails app. any info is greatly appreciated

### PR DESCRIPTION
**Pull request by a-lavis**
Fixes #11

This issue was caused by 46d41c260d633bed0fa9426672435b0bb4796659.
I changed the name of the gem, but neglected to update the module structure to match.  Bundler has a convention of requiring modules based on the gem's name.

### CODE REVIEW

File: test/mail_autorequire_test.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
+require_relative 'test_helper'
+require 'open3'
```
Comment (a-lavis) [inline test/mail_autorequire_test.rb:2]: This is a Ruby standard library module that just helps you run subprocesses and capture stdout/stderr/status code from them.

File: test/mail_autorequire_test.rb [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+
+class MailAutorequireTest < Minitest::Test
+  PROJECT_ROOT = File.expand_path('..', __dir__)
+
+  def test_bundler_default_require_loads_smtpapi_extension
+    out, err, status = run_bundle_ruby('require "bundler"; Bundler.require(:default); require "mail"; puts Mail.new.respond_to?(:smtpapi)')
```
Comment (a-lavis) [inline test/mail_autorequire_test.rb]: We couldn't just test this by doing `assert Mail.new.respond_to?(:smtpapi)` because that test would have passed with or without the `require_relative`s I added.  We needed to actually test `require`ing the gem from scratch.

File: lib/mail_x_smtpapi/version.rb [hunk 3]
```diff
@@ -1,3 +1,3 @@
 module MailXSMTPAPI
-  VERSION = '1.4.0'
+  VERSION = '1.4.1'
```
Comment (amancevice) [inline lib/mail_x_smtpapi/version.rb:2]: no need to bump this because my release failed lol

File: test/mail_autorequire_test.rb (hunk 2 above)
Comment (amancevice) [reply test/mail_autorequire_test.rb]: these might look nicer with HEREDOC:

```ruby
out, err, status = run_bundle_ruby <<~RUBY
  require 'bundler/require'
  require 'mail'
  puts Mail.new.respond_to?(:smtpapi)
RUBY
```

File: test/mail_autorequire_test.rb [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+    assert status.success?, "Expected script to succeed, got:\n#{err}"
+    assert_equal "true\n", out
+  end
+
+  def test_slash_form_is_requireable
+    out, err, status = run_bundle_ruby('require "mail/x_smtpapi/ksr"; require "mail"; puts Mail.new.respond_to?(:smtpapi)')
+
+    assert status.success?, "Expected script to succeed, got:\n#{err}"
+    assert_equal "true\n", out
```
Comment (amancevice) [inline test/mail_autorequire_test.rb]: might be nicer to do 
```ruby
assert_equal 'true', out.chomp
```

**Review by amancevice — APPROVED** [review]
some suggestions but otherwise LGTM

File: lib/mail_x_smtpapi/version.rb (hunk 3 above)
Comment (amancevice) [reply lib/mail_x_smtpapi/version.rb:2]: actually nvm, because I'm going to try to release v1.4.0 now to see if it works

File: test/mail_autorequire_test.rb (hunk 2 above)
Comment (a-lavis) [reply test/mail_autorequire_test.rb]: great call! done in 9dc420ef60bd0044b32bd7e15469a537e25db235

File: test/mail_autorequire_test.rb (hunk 4 above)
Comment (a-lavis) [reply test/mail_autorequire_test.rb]: great call! done in 9dc420ef60bd0044b32bd7e15469a537e25db235
